server:
   port: 8080

spring:
  profiles:
     active: prod
  dataSource:
     url: jdbc:mysql://localhost:3306/test
     username: root
     password: 1234
     driverClassName: com.mysql.jdbc.Driver